# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/add_video.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.video_dir = QtWidgets.QLineEdit(Dialog)
        self.video_dir.setObjectName("video_dir")
        self.horizontalLayout.addWidget(self.video_dir)
        self.video_dir_B = QtWidgets.QPushButton(Dialog)
        self.video_dir_B.setMaximumSize(QtCore.QSize(30, 16777215))
        self.video_dir_B.setObjectName("video_dir_B")
        self.horizontalLayout.addWidget(self.video_dir_B)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.video_nav = QtWidgets.QLineEdit(Dialog)
        self.video_nav.setObjectName("video_nav")
        self.horizontalLayout_4.addWidget(self.video_nav)
        self.video_nav_B = QtWidgets.QPushButton(Dialog)
        self.video_nav_B.setMaximumSize(QtCore.QSize(30, 16777215))
        self.video_nav_B.setObjectName("video_nav_B")
        self.horizontalLayout_4.addWidget(self.video_nav_B)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.extract_img = QtWidgets.QCheckBox(Dialog)
        self.extract_img.setObjectName("extract_img")
        self.gridLayout.addWidget(self.extract_img, 0, 0, 1, 1)
        self.img_st = QtWidgets.QCheckBox(Dialog)
        self.img_st.setEnabled(False)
        self.img_st.setObjectName("img_st")
        self.gridLayout.addWidget(self.img_st, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.st = QtWidgets.QLineEdit(Dialog)
        self.st.setEnabled(False)
        self.st.setMaximumSize(QtCore.QSize(40, 16777215))
        self.st.setObjectName("st")
        self.horizontalLayout_3.addWidget(self.st)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setEnabled(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        self.img_overlap = QtWidgets.QCheckBox(Dialog)
        self.img_overlap.setEnabled(False)
        self.img_overlap.setObjectName("img_overlap")
        self.gridLayout.addWidget(self.img_overlap, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.overlap = QtWidgets.QLineEdit(Dialog)
        self.overlap.setEnabled(False)
        self.overlap.setMaximumSize(QtCore.QSize(40, 16777215))
        self.overlap.setObjectName("overlap")
        self.horizontalLayout_2.addWidget(self.overlap)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setEnabled(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        self.extract_img.toggled['bool'].connect(self.img_st.setEnabled) # type: ignore
        self.extract_img.toggled['bool'].connect(self.img_overlap.setEnabled) # type: ignore
        self.extract_img.toggled['bool'].connect(self.st.setEnabled) # type: ignore
        self.extract_img.toggled['bool'].connect(self.overlap.setEnabled) # type: ignore
        self.extract_img.toggled['bool'].connect(self.label_2.setEnabled) # type: ignore
        self.extract_img.toggled['bool'].connect(self.label_3.setEnabled) # type: ignore
        self.img_overlap.toggled['bool'].connect(self.img_st.setDisabled) # type: ignore
        self.img_st.toggled['bool'].connect(self.img_overlap.setDisabled) # type: ignore
        self.img_overlap.toggled['bool'].connect(self.st.setDisabled) # type: ignore
        self.img_st.toggled['bool'].connect(self.overlap.setDisabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add video"))
        self.label.setText(_translate("Dialog", "Video directory:"))
        self.video_dir_B.setText(_translate("Dialog", "..."))
        self.label_4.setText(_translate("Dialog", "Video navigation(fac.):"))
        self.video_nav_B.setText(_translate("Dialog", "..."))
        self.extract_img.setText(_translate("Dialog", "Extract images"))
        self.img_st.setText(_translate("Dialog", "Fixed sampling time"))
        self.label_2.setText(_translate("Dialog", "s"))
        self.img_overlap.setText(_translate("Dialog", "Fixed image overlap"))
        self.label_3.setText(_translate("Dialog", "%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
